### ISSUE TITLE
Contracts show the 1.5 rewardsfactor after editing it to 1.0 in MP

### ISSUE THREAD

**Issue by Sandertjee** [GMNGjoy/FS25_ContractBoost#11]
Hi,

I edited the rewardFactor to 1.0 on our dedicated server. This results in the actual reward being 1.0 instead of 1.5 which is correct. However, the contract menu still shows prices with 1.5x the amount.

Example:
Contract shows amount 6185
Actual reward amount: 4123

**Comment by GMNGjoy** [comment]
Thank you for your report!  I'll have to get on MP to get some debug information about how this works (or isn't working, as the case may be) - I'll have to look into the configuration file loading and where it should be to be able to get the proper boost.

A few questions to help me debug:
- To confirm, have you restarted the server after making the changes to the configuration file?
- Where did that configuration file need to be for the mod to load it? 
- IF you set the `debugMode` to `true` - do you see additional debug information in the server's log?

**Comment by Sandertjee** [comment]
Hi,

- Yes, server has been restarted
- Config file is in the ModSettings folder in the main files of the server, so outside of the savegame folder.
- Found the following in log files for contractboost with debug settings enabled:

> 2024-12-03 15:44 -- ContractBoost :: loadMapData
> 2024-12-03 15:44 -- ContractBoost:MissionBalance :: settings updated.
> 2024-12-03 15:44 -- ContractBoost:MissionBalance :: scaleMissionReward
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 1: baleMission | updated 2200 => 3500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 2: baleWrapMission | updated 300 => 500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 3: plowMission | updated 2800 => 2800
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 4: cultivateMission | updated 2300 => 2300
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 5: sowMission | updated 2000 => 2000
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 6: harvestMission | updated 2500 => 2500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 7: hoeMission | updated 1500 => 1500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 8: weedMission | updated 2000 => 2000
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 9: herbicideMission | updated 1500 => 1500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 10: fertilizeMission | updated 1500 => 1500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 11: mowMission | updated 2500 => 2500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 12: tedderMission | updated 1500 => 1500
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 13: stonePickMission | updated 2200 => 2200
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 14: deadwoodMission | updated 150 => 150
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 15: treeTransportMission | updated 255 => 255
> 2024-12-03 15:44 ---- ContractBoost:MissionBalance :: Mission 16: destructibleRockMission | updated 550 => 550
> 2024-12-03 15:44 -- ContractBoost:MissionBalance :: scaleMissionReward complete.
> 2024-12-03 15:44 -- ContractBoost :: loadMapData complete.

BaleMission and BaleWrapMission we have left with default so these could be inflated which is correct.

**Comment by GMNGjoy** [comment]
I've been unable to reproduce the issue - feel free to reopen if you see this happening again.
