### ISSUE TITLE
Server stürzt immer ab wenn man Maschinen mietet 

### ISSUE THREAD

**Issue by sunrise19995** [GMNGjoy/FS25_ContractBoost#12]
Hallo , kann es denn sein das der Server immer abstürzt wenn man per Aufträge die Geräte leiht oder normal im Händler Maschinen mieten möchte? Wir hatten das jetzt schon 2x . Eventuell passt da irgendwas mit dem Mod nicht . Ansonsten ein klasse Mod wo es sich wenigstens lohnt Aufträge zu machen 

English Translation:
> Hello, is it possible that the server always crashes when you rent the equipment via orders or want to rent machines normally from the dealer? We've had this happen twice now. There might be something wrong with the mod. Otherwise a great mod where it's at least worth doing orders

**Comment by GMNGjoy** [comment]
Thank you for the report.

There is a potential that this mod is causing that crash - it would be greatly beneficial to have more context on how or what is happening when that crash happens on your server.

Can you provide:
- Detailed description of what type of contract that equipment was being borrowed for as well as if that contract included "free" stuff (pallets of fertilizer, seed or herbicide)
- Any server logs that you'd be willing to provide at the time of the crash - usually the last few lines of the log will be incredibly helpful in debugging the issue.

-----

As a temporary fix, on your server, you can set the value of `enableFieldworkToolFillItems` to `false` in the `ContractBoost.xml` configuration file which would turn off the extra free stuff, but also prevent the crash from happening.

```
enableFieldworkToolFillItems>false</enableFieldworkToolFillItems>
```

**Comment by GMNGjoy** [comment]
@sunrise19995 I'm going to close this for now as I have not heard back from you - please feel free to re-open with log files showing the crash.

**Comment by sunrise19995** [comment]
Hello ,the Admin from the Game Server deleted all Mods on his own Game Server , i can you Not give Back a feedback sry

Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GMNGjoy** [comment]
> Hello ,the Admin from the Game Server deleted all Mods on his own Game Server , i can you Not give Back a feedback sry Gesendet von Outlook für Android<https://aka.ms/AAb9ysg>

No worries, feel free to open this ticket again, or open a new one if the problem persists.
