### ISSUE TITLE
[BUG] customMaxPerType not working as expected.

### ISSUE THREAD

**Issue by MisterMedion** [GMNGjoy/FS25_ContractBoost#16]
Hey ich hätte hier einige Vorschläge für die Verbesserung von Missionen:

Holz-Missionen deaktivieren / Im Einstellungsmenü die verschiedenen Missionstypen aktivieren/deaktivieren.
Einzelne Missionen aus der Verfügbarkeitsliste löschen ohne sie anzunehmen -> Mission verweigern
Per Knopfdruck Missonen neu laden -> es werden neue Missionen mit zb. anderen Feldfrüchten generiert
Pappel-Missionen
Bonus-System wenn man für den selben Besitzer mehrere Aufträge abschliesst

_Google-translated_
> Hey, I have a few suggestions for improving missions:
> - Deactivate wood missions / Activate/deactivate the different mission types in the settings menu.
> - Delete individual missions from the availability list without accepting them -> refuse mission
> - Reload missions at the touch of a button -> new missions with other crops, for example, are generated
> - Poplar missions
> - Bonus system if you complete multiple orders for the same owner

**Comment by GMNGjoy** [comment]
All great ideas!

> Deactivate wood missions / Activate/deactivate the different mission types in the settings menu.

Coming in the next release.

> Delete individual missions from the availability list without accepting them -> refuse mission

Interesting concept, but should be doable - I'll add this to the feature request list

> Reload missions at the touch of a button -> new missions with other crops, for example, are generated

Reloading missions is on my development list, but it may not be possible to _refuse_ a mission, then re-generate, and not see the same mission again. the "other crops" would only be based on the farmlands on the map and the crops they have in them, I wouldn't be able to _change_ the crop type already in a field.

> Poplar missions

I think this would fall under baling missions - assuming that the whole system was setup for that. this one would probably need to be a separate mod.

> Bonus system if you complete multiple orders for the same owner

Gamification of the mission system was something that was already a feature of the "Better Contracts" mod, and I would be "stealing their idea" if i added it to my mod also.  i'll let them handle it

**Comment by Mmtrx** [comment]
Hi @GMNGjoy - thanks for the hint to my BetterContracts mod 😉 .

> Delete individual missions from the availability list without accepting them -> refuse mission

This can be achieved by accept-then-cancel the mission.  Even tree transport missions don't call up penalties if cancelled immediately. 
 
> Reload missions at the touch of a button -> new missions with other crops, for example, are generated

see [FS25_BetterContracts](https://github.com/Mmtrx/FS25_BetterContracts/releases/tag/1.0.1.0)
 
> Bonus system if you complete multiple orders for the same owner

I'm currently working on that

**Comment by MisterMedion** [comment]
Hey
Currently i use the V1.0.2.2
Unfortunatley the Setting customMaxPerType in the default Config works not for me. i set deadwood and treetransport first to 0 then to 1 and test it in the game. I accept & delete all of them and check if they come back. unfortunately in any case i have 5 of both types all the time,

**Comment by GMNGjoy** [comment]
Should be fixed in [1.0.5.0](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.5.0)
