### ISSUE TITLE
Collection of grass and hay from tedding/mowing missions not possible

### ISSUE THREAD

**Issue by nitroSkirata** [GMNGjoy/FS25_ContractBoost#17]
Hey,

If i read the description orrectly, we should be able to bale the grass from mowing and hay from tedding missions.

At least for me it seems not possible.

**Comment by GMNGjoy** [comment]
That is currently incorrect in the `1.0.0.0` version that is on ModHub. As of today, collecting grass is only enabled from MOWING missions. The next release will include TEDDING missions also, with the addition of allowing windrowers, balers & forageWagons to pick up the hay.
