### ISSUE TITLE
Suggestion Pressing Missions

### ISSUE THREAD

**Issue by Heroflooo** [GMNGjoy/FS25_ContractBoost#18]
Hello,

Do you have a possibility to integrate the fact of recovering bales of straw, grass or other when there are pressing missions?

**Comment by GMNGjoy** [comment]
Done. Included as part of the [latest release: 1.0.2.1](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.2.1).

Please let me know if you have any issues.
