### ISSUE TITLE
Custom Rewards

### ISSUE THREAD

**Issue by jufcar** [GMNGjoy/FS25_ContractBoost#2]
hi there
just installed your mod and i tried to get behind the meaning of the custom rewards.
`     <baleMission>3500</baleMission>`
`     <baleWrapMission>500</baleWrapMission>`
Could you elaborate, how these values work? As all other values from other settings are only single or double digit and are easy to understand.

**Comment by GMNGjoy** [comment]
@jufcar I've updated the [README](https://github.com/GMNGjoy/FS25_ContractBoost/blob/main/README.md) to include the above content to make sure that it's widely known, including per-setting default values from the game engine
