### ISSUE TITLE
ContractBoost to work in Dedicated Server

### ISSUE THREAD

**Issue by FarmerDonut** [GMNGjoy/FS25_ContractBoost#23]
Hello!

I'm using your contract boost mod everyday, but recently me and my mates decided to get a Dedicated Server to play on. Mostly so that we did not need to depend on one person to be available to host the game session every time. So we put all of our mods in the dedicated server and started playing, but with an increased economy and so many things to do, we ran quickly low on money.

So we knew we could increase the ContractBoost ModSettings as we had done before, and it works perfectly in Multiplayer and Single Player. But for some reason it won't work on Dedicated Server. Not knowing what to do with the mod to make it work, we decided to try and change the mod file itself, but that did not work. So we deleted that and redownloaded the mod to reset everything.

My question is then pretty simple. How do we get to adjust the modsetting file for ContractBoost when running the mod on a dedicated server? And yes, we did import our save game from the Session Host so we could continue on the save file. But we really want to up the reward multiplier mostly but we don't know how. So if you have any help to fix our issue, we would be grateful as we love the mod!

**Comment by GMNGjoy** [comment]
The answer today and the answer tomorrow may be different - as the settings file (which is typically put in the `modSettings/` folder) will be moving from it's current location to the savegame folder in the next release (alongside a full UI for all of the settings)

I'll add something to the README on how to properly set it up for a dedicated server, and keep that updated once we move to the next version, does that sound good? I'll leave this open for now until I get that documentation written.

**Comment by GMNGjoy** [comment]
Current (version 1.0.2.1 and under) process to change Contract Boost settings on a dedicated server is as follows:

1. Setup dedicated server.
2. Activate Contract Boost, start a game, save said game.
3. Stop server.
4. Open FTP connection to the server
5. Navigate to the `modSettings` folder on the server.
6. Download, edit, re-upload the `ContractBoost.xml` settings file.
7. Re-start server to see the changes.

![Screenshot 2024-12-15 103846](https://github.com/user-attachments/assets/84bfeba1-28cb-4c9f-a41a-44373db668a8)

Note: this process _requires_ FTP access to your dedicated server, which I fully understand is not available on all server hosts. 

-----

The future release (`1.1.0.0`) that I'm currently working on will _depreciate_ the core settings file, and rely on a per-savegame settings that will be customizable in-game, which should be more portable and have settings that are cross-save.

**Comment by Saerens29th** [comment]
Unsure if I should open a new issue, might be related to this. 

On dedicated server, max contracts active remains 3. While set to 10.
We are running version 1.0.3.4.
Is this a known bug for dedicated server? Or do I need to change a value in an xml on the server for it to work?

**Comment by FarmerTreanor** [comment]
> Unsure if I should open a new issue, might be related to this.
> 
> On dedicated server, max contracts active remains 3. While set to 10. We are running version 1.0.3.4. Is this a known bug for dedicated server? Or do I need to change a value in an xml on the server for it to work?

This works on both my local and dedicated server currently had 10 contacts taken out no problem.

**Comment by ShadowDaemon01** [comment]
> > Unsure if I should open a new issue, might be related to this.
> > On dedicated server, max contracts active remains 3. While set to 10. We are running version 1.0.3.4. Is this a known bug for dedicated server? Or do I need to change a value in an xml on the server for it to work?
> 
> This works on both my local and dedicated server currently had 10 contacts taken out no problem.

Hmm, then it's something local on our end. Weird that it works for you, could use some help in figuring it out.

**Comment by GMNGjoy** [comment]
> Hmm, then it's something local on our end. Weird that it works for you, could use some help in figuring it out.

a dedicated server w/ contract boost at this time is not coded to the full level it needs to be reliable to all players in a MP setting. I'm testing a new version now to support this use case.

**Comment by ShadowDaemon01** [comment]
> > Hmm, then it's something local on our end. Weird that it works for you, could use some help in figuring it out.
> 
> a dedicated server w/ contract boost at this time is not coded to the full level it needs to be reliable to all players in a MP setting. I'm testing a new version now to support this use case.

Oh that explains! I did see your comment of it being in development about 2 weeks ago.
Thank you, for now we'll have to wait.

**Comment by GMNGjoy** [comment]
> Oh that explains! I did see your comment of it being in development about 1 weeks ago.
> 
> Thank you, for now we'll have to wait.

Fix is in progress and my current top priority. hoping to get a fix out this week.

**Comment by GMNGjoy** [comment]
This should be fixed with [1.0.4.0](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.4.0

Please re-open if the latest release does not solve your issue.
