### ISSUE TITLE
Not working on MP

### ISSUE THREAD

**Issue by MikoModding** [GMNGjoy/FS25_ContractBoost#3]
Does not work for multiplayer. Tried to join a new server with the mod and it didn't let anyone in. We deactivated it and it is now letting us all in. We checked LOG files and seen this error. 

```
2024-11-26 15:33 Error: Running LUA method 'update'.
D:/home/sid_7275133/farmingSim_2025/profile/mods/FS25_ContractBoost/scripts/MissionBalance.lua:36: attempt to perform arithmetic (mul) on nil and number
```

**Comment by matze0301** [comment]
Maybe it's a conflict with another Mod?
Works on my dedi server like a charm, no errors so far.

> Does not work for multiplayer. Tried to join a new server with the mod and it didn't let anyone in. We deactivated it and it is now letting us all in. We checked LOG files and seen this error.
> 
> ```
> 2024-11-26 15:33 Error: Running LUA method 'update'.
> D:/home/sid_7275133/farmingSim_2025/profile/mods/FS25_ContractBoost/scripts/MissionBalance.lua:36: attempt to perform arithmetic (mul) on nil and number
> ```

**Comment by MikoModding** [comment]
Oh, we will have a go at playing about to see what works :) thanks

**Comment by DaPlum05** [comment]
Hi guys, how are you getting this to work on MP dedi servers? I have added it with no issues, just had a contract offering 23k, did the mission and was paid out 7k? Is the xml edited clinet side or does the xml also need to be in the server files?

**Comment by GMNGjoy** [comment]
> Hi guys, how are you getting this to work on MP dedi servers? I have added it with no issues, just had a contract offering 23k, did the mission and was paid out 7k? Is the xml edited client side or does the xml also need to be in the server files?

DaPlum- it sounds like that's a separate issue than the OP reported - please create a new issue so that I can track it, please post the server logs / screenshots / SOMETHING TO GO ON... the information you've given is hearsay unless you can show me when it happened.
