### ISSUE TITLE
Einstellung werden nicht abgespeichert bzw geladen auf Server

### ISSUE THREAD

**Issue by Taylor1684** [GMNGjoy/FS25_ContractBoost#30]
Wenn ich Auf dem Dedi-Server Einstellungen vornehme, werden diese nicht richtig abgespeichert. 
Es werden immer die Daten geladen was in der XmlConfigManager.lua steht, Ändere ich die Werte dort ab (Zeile 35 - 47), dann werden auch diese Werte genommen. (Die andere Einstellungen habe ich nicht entdeckt) ;-)
Stelle ich alles im Singleplayer ein, wo es funktioniert und kopiere die Datei FS25_ContractBoost (Datei wird auf dem Server beim ersten Start angelegt) vom Savegame in das Savegame vom Server, dann bleibt alles genauso wie es in der XmlConfigManager.lua steht.

[Server-Log.txt](https://github.com/user-attachments/files/18172980/Server-Log.txt)

_English Translation_
> If I make settings on the dedicated server, they are not saved correctly.
> The data that is in the XmlConfigManager.lua is always loaded. If I change the values ​​there (lines 35 - 47), then these values ​​are also used. (I haven't discovered the other settings) ;-)
> If I set everything in single player where it works and copy the FS25_ContractBoost file (file is created on the server when it is started for the first time) from the savegame to the server savegame, then everything stays exactly as it is in the XmlConfigManager.lua.

**Comment by Taylor1684** [comment]
Thanks that you will look for it

**Comment by Justice-Molton** [comment]
Yes, i can confirm, we've got the same issue

**Comment by FabiMaldini** [comment]
Wir haben das gleiche Problem. Des weiteren ist mir aufgefallen das jeder die Einstellungen bearbeiten kann ohne Admin zu sein.
Könnte man die Einstellungen zu Spieleinstellungen hinzufügen anstatt den allgemeinen Einstellungen?

**Comment by GMNGjoy** [comment]
duplicate of #23; This is related to dedicated servers, and the incorrect sync of settings between server and client.
