### ISSUE TITLE
Can´t close Bale Mission

### ISSUE THREAD

**Issue by Taylor1684** [GMNGjoy/FS25_ContractBoost#31]
When i have the "CollectingBalesFromMissions" of true, then i can close the mission. But when it false it can´t close the Mission. It is on hostet Multiplayer. 
On Server can´t close the Mission regardless of whether with false or true.

2024-12-18 12:34 Error: Running LUA method 'update'.
C:/Users/andre/OneDrive/Dokumente/My Games/FarmingSimulator2025/mods/Multiplayer/FS25_ContractBoost/scripts/MissionTools.lua:156: attempt to call a table value

In Singleplayer i can´t say know.

Use version 1.0.3.3

[Log_Ballen pressen.txt](https://github.com/user-attachments/files/18180851/Log_Ballen.pressen.txt)

**Comment by GMNGjoy** [comment]
I'll confirm, and see what I can do to fix, thanks for reporting!

**Comment by Draakii** [comment]
I also get the same error using 1.0.3.3 on dedicated server.  The same thing happens with bale wrapping missions.

Thanks for the mod and all your hard work <3

**Comment by GMNGjoy** [comment]
i’m actively working on a fix. i should have something released by
tomorrow.

**Comment by GMNGjoy** [comment]
Potential fix released: [1.0.3.4](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.3.4} please let me know if it fixs the problem for everyone who is affected!

**Comment by FarmerTreanor** [comment]
your fix works can now pickup bales using auto loader thank you

**Comment by FarmerTreanor** [comment]
Unsure what going on now the in game autoloader not allowing the bales picked up now before using the UAL (Universal Autoload ) but that also just stopped working.

**Comment by GMNGjoy** [comment]
> Unsure what going on now the in game autoloader not allowing the bales picked up now before using the UAL (Universal Autoload ) but that also just stopped working.

Please open a separate issue - this issue is surrounding the use case when the `enableCollectingBalesFromMissions` flag is turned _off_, which would mean that the bales are not yours and you shouldn't be able to pick them up. Please include the version you are currently using, and a copy of your log file when reporting.

**Comment by FarmerTreanor** [comment]
no problem

**Comment by Taylor1684** [comment]
Danke fürs fixen das man die Missionen jetzt abschließen kann.
Aber jetzt, wenn ich die Mission abschließe verschwinden die Ballen bei beiden Moduse.
Außer wenn ich den Ballen in Objectlager tu bleibt er erhalten, aber verkaufen geht nicht da der Ballen keine farm ID hat.
 Wäre es eine lösung bei CollectingBalesFromMissions "True", denn Ballen eine Farm ID zu geben?

I have new Lua call stack,, know.

2024-12-19 21:11 LUA call stack:
  =dataS/scripts/misc/ItemSystem.lua:288 removeItem
  =dataS/scripts/objects/Bale.lua:121 delete
  =dataS/scripts/missions/field/BaleMission.lua:187 finishField
  =C://gameservers//s1495141//ls2025//gameProfile/mods/FS25_ContractBoost/scripts/MissionTools.lua:156 finishBaleField
  =dataS/scripts/utils/Utils.lua:601 
  =dataS/scripts/missions/field/AbstractFieldMission.lua:338 dismiss
  =dataS/scripts/missions/MissionManager.lua:502 dismissMission
  =dataS/scripts/missions/events/MissionDismissEvent.lua:74 run
  =dataS/scripts/missions/events/MissionDismissEvent.lua:54 readStream
  =dataS/scripts/network/Server.lua:538 packetReceived
  =dataS/scripts/network/ConnectionManager.lua:27 packetReceived
2024-12-19 21:11 
Script error in removeTrigger: Unknown entity id 651984 for 'triggerNodeId' in method 'removeTrigger'.

LUA call stack:
  =[C]:-1 removeTrigger
  =dataS/scripts/objects/MountableObject.lua:47 delete
  =dataS/scripts/objects/Bale.lua:122 delete
  =dataS/scripts/missions/field/BaleMission.lua:187 finishField
  =C://gameservers//s1495141//ls2025//gameProfile/mods/FS25_ContractBoost/scripts/MissionTools.lua:156 finishBaleField
  =dataS/scripts/utils/Utils.lua:601 
  =dataS/scripts/missions/field/AbstractFieldMission.lua:338 dismiss
  =dataS/scripts/missions/MissionManager.lua:502 dismissMission
  =dataS/scripts/missions/events/MissionDismissEvent.lua:74 run
  =dataS/scripts/missions/events/MissionDismissEvent.lua:54 readStream
  =dataS/scripts/network/Server.lua:538 packetReceived
  =dataS/scripts/network/ConnectionManager.lua:27 packetReceived

Server Log attached
[Server-Log 241219.txt](https://github.com/user-attachments/files/18202893/Server-Log.241219.txt)

**Comment by Michl7** [comment]
Fix works for me, thx.
