### ISSUE TITLE
Avavailable missions per type

### ISSUE THREAD

**Issue by DrDrulia** [GMNGjoy/FS25_ContractBoost#32]
This mod is great, but one annoying feature is increasing the number of available missions per type. I want harvest contracts, not 10 dead wood and timber deliveries if it's harvest season. Would it be better to multiply the default settings?

**Comment by DrDrulia** [comment]
I did not see a new update. Sorry

**Comment by GMNGjoy** [comment]
> I did not see a new update. Sorry

I hope that the latest update with all of the settings in the in-game menu (and the ability to both increase all the contracts at once, or individually customize) meets the needs of your request! Thanks for thinking to report either way!
