### ISSUE TITLE
[FEATURE]  Change Settings in UI from "General Settings" to "Game Settings"

### ISSUE THREAD

**Issue by Sani9000** [GMNGjoy/FS25_ContractBoost#42]
Hi Josh,
I really appreciate the modification and am happy to see the good progress. Thank you for the work you put in! :)

Adding settings to the UI is an absolute milestone, but as an administrator of a multiplayer server I am not entirely happy that now every player (and not just the administrators) can change the default settings according to their "needs" - the "General Settings" tab is accessible to every player by default.

I would really appreciate if the settings were moved to the "Game Settings" tab or there was a way to give priority to the XML in the modSettings directory (e.g. a "forceXMLSettings = true|false" function).

Can this be done? Or have I missed something?

Merry Christmas and best wishes from Germany!

Cheers, Martin

**Comment by GMNGjoy** [comment]
This is already fixed in the test build, only administrators will have access to settings, and the settings can only be saved on the server side. 

there is currently a sync issue between server and client, but i'm actively working on a fix.

**Comment by GMNGjoy** [comment]
Fixed with https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.4.0

**Comment by Sani9000** [comment]
Perfect, thank you! :)
