### ISSUE TITLE
[BUG] Noticeable delay when opening/scrolling through menus

### ISSUE THREAD

**Issue by BurcoGames** [GMNGjoy/FS25_ContractBoost#45]
**Version & Platform**
 - Version [`1.0.5.0`] (this was happening in `1.0.3.4` as well)
 - Singleplayer

**Describe the bug**
There is a noticeable delay/framerate drop when opening/scrolling through menus (like the map, settings page, PowerTools menu, etc.). This is a very minor "bug", but can be slightly jarring. The delay seems to be roughly half a second or less. This occurs both when only this mod is selected, and when in a full list of mods (~70 currently). Deselecting this mod removes the aforementioned delay.

**To Reproduce**
1. Load into the game with mod active
2. Open any menu (map, settings page, PowerTools menu)

**Expected behavior**
In theory, there should be no delay opening any menus and should be smooth going between them.

**Log files**
Log shows no errors or warnings related to this, as far as I can tell, but I'll include it anyway.
[log.txt](https://github.com/user-attachments/files/18259903/log.txt)

**Comment by GMNGjoy** [comment]
Thanks for the report @BurcoGames, I'll take a look. I suspect it has to do with the UI menu that we've added, but I don't know if there's anything we can do about it.

**Comment by FirenzeIT** [comment]
Yes, I confirm that too, it happens to me with the latest version (releases) 1.0.5.0. Without the mod installed, the menus are all smooth; however when I open the same in-game while with the mod installed, it lags quite a bit.

**Comment by GMNGjoy** [comment]
> Yes, I confirm that too, it happens to me with the latest version (releases) 1.0.5.0. Without the mod installed, the menus are all smooth; however when I open the same in-game while with the mod installed, it lags quite a bit.
> 
> PS.: it's possible add inside a Refresh Contracts + Clear all contracts??

_Please_ post suggestions or feature requests as their own issue, not appending to other people's completely unrelated issues. 

...and No, that feature will not be part of **Contract Boost**. That feature will be handled by [FS25_BetterContracts](https://github.com/Mmtrx/FS25_BetterContracts), which is intended to live side by side with this mod.

**Comment by FirenzeIT** [comment]
No, because i don't use BetterContracts (only one at once, just for tried), so i use only ContractBoost..

**Comment by GMNGjoy** [comment]
@BurcoGames We've been testing this bug report (thank you for the detailed report), but at this time we're not able to replicate any noticeable delay when opening or going between menus. 

The only thing that this mod does is add a somewhat large number of options to the general settings menu, after which - it's up to the game engine to render those properly. I can only guess that the game engine isn't optimized properly for long menus within the settings menu area.

At this time, there's nothing we can do that's actionable other than potentially disabling the addition of the menu entirely. Since all of the settings also live in a preferences file that is user editable, the only thing I can think of would be to add a configuration option (that would be true by default and not accessible in the UI) something like `enableInGameSettingsMenu` - and let you (or anyone else experiencing that same delay and wanting to do something about it) to disable the menu entirely. Other than that, it's  not a delay that I have any control over.

Thoughts? Would you like that setting, or no?

**Comment by BurcoGames** [comment]
@GMNGjoy I appreciate you looking into this. If nothing else, I think that config option could be useful not only to me but others as well, so yeah that would be nice to have, if it's easy to implement.

I did have a thought, however - I know mods like Courseplay have an entirely separate menu for all the configurations, so would that be something that could solve this? Basically a dedicated menu with all the options and a keybind to access said menu.

Just an idea, if that wouldn't work, then of course the solution you provided would work just fine.

**Comment by GMNGjoy** [comment]
> I did have a thought, however - I know mods like Courseplay have an entirely separate menu for all the configurations, so would that be something that could solve this? Basically a dedicated menu with all the options and a keybind to access said menu.
> 
> Just an idea, if that wouldn't work, then of course the solution you provided would work just fine.

This would be the only other "solution" which would take a significant amount of work, but may or may not solve the "issue"; it doesn't make sense to dive into that deep of a rewrite without knowing what the root cause is. I'll see about adding a config param, and we can take it from there.

**Comment by BurcoGames** [comment]
> This would be the only other "solution" which would take a significant amount of work, but may or may not solve the "issue"; it doesn't make sense to dive into that deep of a rewrite without knowing what the root cause is. I'll see about adding a config param, and we can take it from there.

That makes sense. Yeah, the config option is a good start, and we'll see what happens. Again, I really appreciate you looking into this.

**Comment by GMNGjoy** [comment]
**done**. [1.0.5.3](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.5.3)

Please let me know if the performance issue / delay is gone with this setting turned off.

**Comment by BurcoGames** [comment]
Just tested it, and I can confirm that the delay is fixed with the in-game settings disabled.

**Comment by GMNGjoy** [comment]
Happy that worked! 👍

**Comment by FirenzeIT** [comment]
I also tested the latest update and confirm the above reported: now with this setting disabled, every menu and switching from one section to another is much faster, smoother, returning as if there was no mod installed, plus I also gained several fps. Very Good work. 👍🏻
