### ISSUE TITLE
[BUG] contract with borrowed items will not be prepared

### ISSUE THREAD

**Issue by Brax-bit** [GMNGjoy/FS25_ContractBoost#46]
**Version & Platform**
 - Version 1.0.5.1 (FS25 1.4.0.0)
 - SinglePlayer

**Describe the bug**
I try to accept a contract with borrowed items. The contract is then prepared but the preparation is not completed even after several minutes. It is then not possible to finish the contract or to accept any other contract because the field is not prepared.
The bug occures also when the only active mod is ContractBoost.
This error only occurs sometimes. Now this happens when I try to accept a plowing (Kubota M8-201, AGRO-MASZ POV 5 XL and TENWINKEL PAC-1000) or deadwood contract (John Deere 843L-II) in my attached savegame.

The only solution I found is to reload the savegame and accept the contract without borrowed items, deactivate ContractBoost or to manually edit and correct the missions.xml and vehicles.xml.

I have already observed this behavior in previous versions of this mod in single (Zilonka) and multiplayer (Riverband Springs). 

**To Reproduce**
1. Start my savegame with only ContractBoost activated
2. Try to start the plowing or deadwood contract with borrowed items
3. See error in 'Active' tab ('Preparing contract ...')

**Expected behavior**
The contract should be prepared like other contracts with borrowed items.

**Screenshots**
![20241228103249_1](https://github.com/user-attachments/assets/5e67dde4-5ae2-4b6a-b93e-410a1f8683c6)
![20241228103256_1](https://github.com/user-attachments/assets/0a0d3f69-3646-4f7c-9ee8-5c89330bf505)
![20241228103302_1](https://github.com/user-attachments/assets/3b4fc55a-a435-4d9f-bd7c-8a6dea5423cf)
![20241228103308_1](https://github.com/user-attachments/assets/5977fbdd-ce22-42d0-96c3-faeab9cae1f8)

**Log files**
Attach your current log file here.
[log.txt](https://github.com/user-attachments/files/18265736/log.txt)

**Comment by Brax-bit** [comment]
[savegame1.zip](https://github.com/user-attachments/files/18265754/savegame1.zip)

**Comment by GMNGjoy** [comment]
@Brax-bit - thank you for the well written bug report! the inclusion of the savegame zip really helped and sped up the process for recreating this issue. 

should be fixed in [1.0.5.2](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.5.2)
