### ISSUE TITLE
[BUG] Display Prices

### ISSUE THREAD

**Issue by PillowyGiant** [GMNGjoy/FS25_ContractBoost#49]
**Version & Platform**
 - Version 1.0.0.2
 - Multiplayer

**Describe the bug**
Friend has one price thats lower than the price I see on my end, All the details are the same like name what needs to be done but the Price for the Reward. IE: My Contract says 15,000- Friend Contract says 5,000 -

**Comment by CombineBert** [comment]
We are having similar, also contracts are paying out one third of the displayed price.  No errors reported in log, will enable debug mode at next reboot.

**Comment by CombineBert** [comment]
Might have found something.  In the defaultConfig.xml is the following line

<rewardFactor>0.5</rewardFactor>

Which on the server is also present in the ContractsBoost.xml.

The ContractsBoost.xml on my PC however shows 1.5.  This file would have been created on my PC with the initial release where as the one on the server would have been created with the newer version when the server went live.

Will update this on the server and report back.

**Comment by PillowyGiant** [comment]
That kind of make sense in a way for Servers might have another config settings but in my case I'm not sure how this would work, I'm running mine from my PC. meaning that I have the 1.5 and my friend who downloaded it the same way as me somehow has the 0.5 though we got it from the same place, Via In-game content....

**Comment by CombineBert** [comment]
Changing the ContractBoost.xml on the server

`<rewardFactor>1.5</rewardFactor>`

Has resolved the issue.

If you installed the mod at release, your ContractBoost.xml in the modsettings folder would have been created with a value of 1.5.  If you installed the mod for the first time after the update, it would have created it at the 0.5.

It gets this from the defaultConfig.xml where it is also incorrect.  I could not find this in the repo (I'm not that great with github) maybe it is created by one of the scripts.  Either way, the base setting is now incorrect.

If your friend corrects the setting in their ContractBoost.xml, you will be good to go.

**Comment by PillowyGiant** [comment]
So I got my friend to look at the xml and told him the line you said and its worked, Not sure how he had a lower one but that was for sure the problem. 0.5 on his end, 1.5 on mine!

**Comment by GMNGjoy** [comment]
Looks like you did a bunch of research on this one @PillowyGiant ... but the real answer is that you're using an outdated version of the mod. The version currently on ModHub is `1.0.0.2` - but the most recent version here on GitHub (which will always have the most up to date version) is [1.0.5.3](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.5.3).

The issue you've posted about was fixed in `1.0.4.0`, about a week ago.

The reason that the version that is on ModHub is so far behind is that there's currently over a month wait for any mod to get posted or updated to ModHub - which means that for mods like this one which I'm fixing stuff almost daily, that GitHub is the best place to stay up to date. I also post to my Discord whenever mods are updated, feel free to [join over there](https://gmngjoy.com/discord) as well!

**Comment by PillowyGiant** [comment]
I mostly use modhub as its easier to use the ingame list, I asummed it was the latest as well, Will have to look at the one here though for sure! A month is stupid but do they even test things over there so it takes longer?

**Comment by GMNGjoy** [comment]
> I mostly use modhub as its easier to use the ingame list, I asummed it was the latest as well, Will have to look at the one here though for sure! A month is stupid but do they even test things over there so it takes longer?

It's mostly unknown what is done as far as testing on the Giants' side... but that month timeframe is just the "wait" time, like waiting in line. then, they test however they test, and you get results. if it fails (regardless of the reason) then you go to the back of the line and... you guessed it! time to wait another month (or more) to get tested again. Giants has made the Department of Motor Vehicles seem like a fast process!

the `1.0.0.2` update (which was a two line change) took over 3 weeks to get out, and that was before GE10 was released, and the floodgates opened.

**Comment by PillowyGiant** [comment]
Pain in the arse if you ask me on waiting... But it is what it is. Thankfully we've updated now and are running it well, sadly the Deadwood contracts are not that great to do as we get something stupid like 5 for 2 maybe 3k a go.

**Comment by GMNGjoy** [comment]
just up the deadwood contracts to 500+ per log, that was the original
basegame setting

**Comment by PillowyGiant** [comment]
Well that did it! thanks for that one too!
