### ISSUE TITLE
Suggestion: Enable Storage and Sale of Bales from Grass and Straw

### ISSUE THREAD

**Issue by firstwOw** [GMNGjoy/FS25_ContractBoost#5]
Suggestion:

Since this mod allows us to pick up grass and straw from contracts, it would be great if it also allowed us to bale the grass and straw, enabling us to store or sell them. Currently, while it is possible to create bales, they remain the property of the landowner and cannot be sold. Allowing players to sell these bales would add more versatility to the gameplay and provide additional ways to manage and profit from the collected resources.

**Comment by GMNGjoy** [comment]
This mod does NOT allow you to pick up bales from baling contracts of any kind. It SPECIFICALLY calls out Mowing missions

> - Allow collecting grass from mowing missions

This mean MOWING missions only, not baling missions of any kind. That said, I'm going to try to allow bales to be collected, that's next on my list of features to add, but it'll be a few weeks.
