### ISSUE TITLE
Sowing contract. The contract start but the % is not moving when sowing

### ISSUE THREAD

**Issue by Gamestyle85** [GMNGjoy/FS25_ContractBoost#6]
After starting a sowing contract the contract start but the % is not moving when sowing. and some of the sowing contract have way to little seeds.

**Comment by emwedk** [comment]
fix here if you're on pc https://steamcommunity.com/app/2300320/discussions/0/6589423877370167684/

**Comment by GMNGjoy** [comment]
I'll test this to confirm, but As @emwedk suggested, this may not be related to this mod.

**Comment by GMNGjoy** [comment]
Closing for now - please feel free to reopen if the issue re-surfaces
