### ISSUE TITLE
Keine Funktion

### ISSUE THREAD

**Issue by foreverls19** [GMNGjoy/FS25_ContractBoost#8]
Hallo,
der mod hat bei mir keine Funktion,
es ist nur der ContravtBoos im modsordner und spiel die Standartkarte,
alles auf dem neusten Stand.
In der  ContractBoost.xml habe ich auch schon den Wert rewardFactor auf 0.5 gestellt ohner Erfolg.

English translation:
> Hello,
> the mod doesn't work for me,
> it's just the _ContractBoost_ in the mods folder and I play the standard map, everything is up to date.
> In the ContractBoost.xml I've already set the `rewardFactor` value to `0.5` without success.

**Comment by GMNGjoy** [comment]
I'm assuming that "doesn't work for me" means that the mod _works_ but your custom setting isn't getting applied as you expect? I'll test it out and let you know!

**Comment by foreverls19** [comment]
Der mod wird laut log geladen, in der ContractBoost.xml kann ich einstellen was ich will, die Preise sind immer gleich

**Comment by xman1971** [comment]
I can;t get it to change my log reward per tree see screenshots
![Screenshot 2024-11-30 183159](https://github.com/user-attachments/assets/0ef409f2-87da-4955-ad64-16d58bb2570c)
![Screenshot 2024-11-30 183454](https://github.com/user-attachments/assets/8059691f-25da-480d-b268-851ce91dd3ac)

**Comment by GMNGjoy** [comment]
> I can;t get it to change my log reward per tree see screenshots ![Screenshot 2024-11-30 183159](https://private-user-images.githubusercontent.com/47463221/391298693-0ef409f2-87da-4955-ad64-16d58bb2570c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTc0MzgsIm5iZiI6MTczMzAxNzEzOCwicGF0aCI6Ii80NzQ2MzIyMS8zOTEyOTg2OTMtMGVmNDA5ZjItODdkYS00OTU1LWFkNjQtMTZkNThiYjI1NzBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAxMzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3NzM3Y2ViZDQ4ODZiOWEzMjZjMzIwNjcyNmRlMGJhYTBiOGQ1ZjVkYzcwNzFlZTZlMGM2OTVhYjNhZWVlZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yB_4CmeJKjkc4AGX2dkoom1g5wwdw705matKt9sscDw) ![Screenshot 2024-11-30 183454](https://private-user-images.githubusercontent.com/47463221/391298762-8059691f-25da-480d-b268-851ce91dd3ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMwMTc0MzgsIm5iZiI6MTczMzAxNzEzOCwicGF0aCI6Ii80NzQ2MzIyMS8zOTEyOTg3NjItODA1OTY5MWYtMjVkYS00ODBkLWIyNjgtODUxY2U5MWRkM2FjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAxVDAxMzg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzNTViYTcxN2RkNDFiMTg4OTJiZDRlMDg1ZmFkMjY2Y2RhNjIyMjNjZmFhYTE5N2FmOGUyMzE2OGJlMzhhMTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ef4ROs9KEasCOTA3-BrxWjAvJtjr1N50Iqc2Zd6uuO4)

@xman1971 please submit a separate issue, your issue is unrelated to the OP.

**Comment by GMNGjoy** [comment]
> Hallo, der mod hat bei mir keine Funktion, es ist nur der ContravtBoos im modsordner und spiel die Standartkarte, alles auf dem neusten Stand. In der ContractBoost.xml habe ich auch schon den Wert rewardFactor auf 0.5 gestellt ohner Erfolg.
> 
> English translation:
> 
> > Hello,
> > the mod doesn't work for me,
> > it's just the _ContractBoost_ in the mods folder and I play the standard map, everything is up to date.
> > In the ContractBoost.xml I've already set the `rewardFactor` value to `0.5` without success.

> Der mod wird laut log geladen, in der ContractBoost.xml kann ich einstellen was ich will, die Preise sind immer gleich
> > English: The mod is loaded according to the log, in the ContractBoost.xml I can set what I want, the prices are always the same

@foreverls19  I'm not able to replicate your issue... when I set the same configuration on my local machine, I've confirmed that the mod does support _lowering_ the boost value with a value of `0.5`... but depending on other settings, it might not "apply" that value.

the logic basically says: "use any reward customization, or use the default rate * reward factor as set in the configuration file."

as an example, if your configuration file looked like this: 

```
 <contractBoost>
    <settings>
        <rewardFactor>0.5</rewardFactor>
     </settings>
     <customRewards>
        <baleMission>3500</baleMission>
      </customRewards>
    </settings>
</contractBoost>
```

then the logic above would use the value of `3500/ha` for `baleMissions` instead of the value of `1100/ha` (default `2200 * 0.5`)

**Comment by foreverls19** [comment]
das steht in meiner log:
![Screenshot 2024-12-01 075222](https://github.com/user-attachments/assets/34bb2f86-25e7-4c52-ac06-16a9e140c5ee)

und das ist die "ContractBoost.xml"
[ContractBoost.txt](https://github.com/user-attachments/files/17968078/ContractBoost.txt)

**Comment by GMNGjoy** [comment]
looks like you might have version `1.0.0.1` - which had a small defect. `1.0.0.2` is on the releases page, does that help?

**Comment by foreverls19** [comment]
Ja Danke, neue Vers. hat geholfen.
Vielen lieben Dank für deine Hilfe und für die Zeit wo du für uns opferst.
Wie kann ich dir was gutes tun?

**Comment by GMNGjoy** [comment]
> Ja Danke, neue Version hat geholfen. Vielen lieben Dank für deine Hilfe und für die Zeit wo du für uns opferst. Wie kann ich dir was gutes tun?

Much appreciated, but obviously not required - If you'd like to do something nice, you could subscribe on my Youtube channel: https://www.youtube.com/@gmngjoy and / or buy me a coffee through https://ko-fi.com/gmngjoy. 

I'm glad I was able to solve your issue!
