### ISSUE TITLE
Grass schwaden und pressen bei Wendeaufträgen | Grass swathing and baling for turning jobs

### ISSUE THREAD

**Issue by H4nnib4l22** [GMNGjoy/FS25_ContractBoost#9]
Hallo :) 

bitte noch hinzufügen das man das Grass schwaden und pressen kann bei den Zetteraufträgen welche es jetzt neu gibt im 25er :) 

VG und Cheers 

Hello :) 

please add that you can swath and press the grass with the tedder orders which are now available in the 25 :) 

VG and Cheers

**Comment by GMNGjoy** [comment]
Good idea, I'll add that in the next major release (`1.0.1.0`)

**Comment by GMNGjoy** [comment]
_Done._ Included as part of the [latest release](https://github.com/GMNGjoy/FS25_ContractBoost/releases/tag/1.0.2.1).
